# Generated by Django 4.1.7 on 2023-03-07 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('column_separator', models.IntegerField(choices=[(0, ';'), (1, ',')], default=1)),
                ('string_character', models.IntegerField(choices=[(0, "'"), (1, '"')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField(choices=[(0, 'Full name'), (1, 'Job'), (2, 'Email'), (3, 'Domain name'), (4, 'Phone number'), (5, 'Company name'), (6, 'Text'), (7, 'Integer'), (8, 'Address'), (9, 'Date')])),
                ('order', models.IntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='schema.schema')),
            ],
        ),
    ]
