# Generated by Django 4.1.7 on 2023-03-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='name',
            new_name='column_name',
        ),
        migrations.RenameField(
            model_name='schema',
            old_name='name',
            new_name='schema_name',
        ),
    ]
