# Generated by Django 4.1.7 on 2023-03-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_rename_name_column_column_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
